namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

tags:
  Environment: '${tag.TagEnvironment}'
  ApplicationOwner: '${tag.TagApplicationOwner}'
  ApplicationID: '${tag.TagApplicationID}'
  AppName: '${tag.TagAppName}'


stacks:
  project-template:
    stack_name: ${namespace}-frontend
    template_path: ./templates/website.yml
    variables:
      pPrefix: ${prefix}
      pAppName: ${appname}
      pEnvironment: ${environment}

post_build:
  upload_artifact:
    path: runway.cfngin.hooks.command.run_command
    required: true
    args:
      command: [
          "upload.bat",
          "${output project-template::WebsiteBucketName}"
      ]


 # "s3://${output project-template::WebsiteBucketName}",